services:
  frontend:
    image: node:16
    user: node
    working_dir: /home/node/app
    volumes:
      - ./src/frontend/:/home/node/app
    ports:
      - "${VUE_PORT:-5000}:${VUE_PORT:-5000}"
    command: "yarn run dev --host 0.0.0.0 --port ${VUE_PORT:-5000}"
  # db:
  #   image: postgres
  #   expose:
  #     - "${DB_PORT:-5432}"
  api:
    build: ./src/backend/
    volumes:
      - ./src/backend/:/home/python/app
    ports:
      - "${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}"
    command: bash -c "\
      poetry install --no-dev --no-interaction --no-ansi && \
      python3 manage.py runserver 0.0.0.0:${DJANGO_PORT:-8000}"
    # depends_on:
    #   - db
  migrate:
    build: ./src/backend/
    volumes:
      - ./src/backend/:/home/python/app
    command: bash -c "\
      poetry install --no-dev --no-interaction --no-ansi && \
      python3 manage.py makemigrations && \
      python3 manage.py migrate"