# Generated by Django 4.2 on 2023-04-17 20:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('togather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='togatheruser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='togatheruser',
            name='creator_score',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='togatheruser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='togather.togatheruser'),
        ),
        migrations.AlterField(
            model_name='togatheruser',
            name='other_sites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='togatheruser',
            name='participant_score',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='togatheruser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
