# Generated by Django 4.2 on 2023-04-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togather', '0002_alter_togatheruser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='togatheruser',
            name='other_sites',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
