# Generated by Django 4.2 on 2023-04-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togather', '0004_alter_event_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='togatheruser',
            name='creator_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='togatheruser',
            name='participant_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
